#!/bin/sh
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "docker" do |d|
	d.build_image "/vagrant/DOCKERFILE_PATH", args: "-t DOCKER_IMAGE_NAME" 
	d.pull_images "mariadb:MARIA_TAG"
	d.run "mariadb", image: "mariadb",  args: "--name amariadb -e MYSQL_ROOT_PASSWORD=MYSQL_PASSWORD"
	d.run "DOCKER_IMAGE_NAME", image: "DOCKER_IMAGE_NAME", args: "--name awpblog --link amariadb:mysql -p 8080:80 -e WORDPRESS_DB_USER=root -e WORDPRESS_DB_PASSWORD=MYSQL_PASSWORD"
  end
  config.vm.network :forwarded_port, guest: 8080, host: 8080
end
